### ISSUE TITLE
提交社区信息

### ISSUE THREAD

**Issue by icepy** [icepy/Front-End-Develop-Guide#2]
| 中文 Front-End Developer 社区列表 | 地址 |
| --- | --- |
| [icepy](http://icepy.github.io) | http://icepy.github.io |

**Comment by tuhaihe** [comment]
推荐一个人人分享技术干货的站点：
- 极客头条：http://geek.csdn.net

当然，这里也有一个更专注于前端的小组：http://geek.csdn.net/forum/47

**Comment by icepy** [comment]
@tuhaihe 已添加，感谢分享～

**Comment by tuhaihe** [comment]
@icepy 多谢 -_^
