### ISSUE TITLE
工作岗位

### ISSUE THREAD

**Issue by icepy** [icepy/Front-End-Develop-Guide#3]
格式：

**职位描述**

15k-30k 某某地 经验3-5年 本科及以上 全职

我们在寻找并肩战斗的小伙伴，我们需要你：

负责（某某）公司（某某）产品的前端开发

**我们希望你：**

充满好奇心，享受coding，学习能力强，有代码洁癖
技术全面，对技术有热情，关注技术发展方向
极强的责任心，追求完美的习惯，刨根问底的精神

**技术上：**

熟练掌握HTML5、CSS3、JavaScript开发

熟悉W3C标准与ES规范，熟悉Web语义化

熟练掌握盒模型、常用布局以及浏览器和移动设备兼容性

熟练使用至少一种JS框架，掌握其原理，能独立开发常用组件

熟练使用各种调试、抓包工具，能独立分析、解决和归纳问题
具有至少一门服务器端编程的实战经验

具有性能优化经验

熟悉各种常用设计模式和常用MV*框架

**你将加入这样一群人：**

追求自由、平等，提倡简单、透明和分享
对新事物充满好奇，对技术充满热情
热爱生活、热爱运动，爱户外、爱篮球、爱羽毛球还有爱二次元的

**工作环境上：**

无时间限制体验apple watch
免费的午餐、晚餐（由大厨掌勺，每天3菜1汤）
免费的果盘（告诉你想吃的，我们立马就换）
定期的运动（羽毛球、篮球都OK，不想出屋的公司也有跑步机）
每次破纪录时的老板红包及霸王杯
其他的，自己来体验吧

**简历投送**

xiangwenwe@foxmail.com / QQ / 微信 / Phone

**Comment by mmk2000** [comment]
哪家公司，都不贴出来？！

**Comment by icepy** [comment]
@mmk2000  这只是模版，期望可以这么写。

**Comment by zacharydigital** [comment]
什么看不懂

**Comment by zacharydigital** [comment]
@icepy @mmk2000

**Comment by yalishizhude** [comment]
噗~~~这是在歪歪么？

**Comment by zacharydigital** [comment]
@yalishizhude 为什么没有邮件提醒啊

**Comment by zachby** [comment]
[](url)
